name: g_kit
publish_to: 'none'
environment:
  sdk: '>=3.6.0 <4.0.0'
resolution: workspace
packages:
  - g_lib
  - g_common
  
scripts:
  bootstrap:
    run: melos bootstrap --scope="g_*"
  analyze:
    run: melos exec -- flutter analyze
  get:
    run: melos exec -- flutter pub get
  test:
    run: melos exec -- flutter test
  outdated:
    run: melos exec -- flutter pub outdated
  generate:
    run: melos exec --depends-on build_runner -- dart run build_runner build --delete-conflicting-outputs
  build_apk:
    run: melos exec --dir-exists=android -- flutter build apk
  build_ios:
    run melos exec --dir-exists=ios -- flutter build ios
