name: g_lib
description: "A new Flutter package project."
version: 0.0.1
homepage: ''
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 유틸성 라이브러리
  path_provider: ^2.1.5          # 파일 경로 관련

  # 스토리지 라이브러리
  sqflite: ^2.4.2               # 로컬 db 데이터베이스

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
